import { DEFAULT_QUESTION_ID, QUESTION_GROUPS, findQuestion } from "./analysis-prompt.js";

const API_URL = "/review-intel/api/workspace";
const DEMO_URL = "/review-intel/workspace-demo.json";
const HISTORY_KEY = "review-intel-workspace-history-v1";
const state = { config: null, accessCode: "", snapshot: null, report: null, questionId: DEFAULT_QUESTION_ID, activeGroup: QUESTION_GROUPS[0].label, warned: false, selectedUrl: "", searchResults: [], activeSearchIndex: -1, searchTimer: null, searchController: null, searchSequence: 0, evidenceTrigger: null, pendingAnalysis: null };
const $ = (selector) => document.querySelector(selector);
const sourceForm = $("#source-form"), appUrl = $("#app-url"), market = $("#market"), limit = $("#review-limit"), sampleButton = $("#sample-button"), samplePanel = $("#sample-panel"), sampleFacts = $("#sample-facts"), sampleCaption = $("#sample-caption"), questionGroups = $("#question-groups"), questions = $("#questions"), modelSelect = $("#model-select"), analyzeButton = $("#analyze-button"), trialNote = $("#trial-note"), warning = $("#consumption-warning"), reportEmpty = $("#report-empty"), reportView = $("#report-view"), liveStatus = $("#live-status"), accessDialog = $("#access-dialog"), evidenceDialog = $("#evidence-dialog"), appResults = $("#app-results");

function initializeAnalytics() {
  if (!["reviews.doubledash.me", "willthiseverwork.com", "www.willthiseverwork.com"].includes(window.location.hostname)) return;
  window.dataLayer = window.dataLayer || [];
  window.gtag = window.gtag || function gtag() { window.dataLayer.push(arguments); };
  const script = document.createElement("script"); script.async = true; script.src = "https://www.googletagmanager.com/gtag/js?id=G-R8F1QX6HKC"; document.head.append(script);
  let referrer = ""; try { const url = document.referrer ? new URL(document.referrer) : null; referrer = url && /^https?:$/.test(url.protocol) ? `${url.origin}/` : ""; } catch {}
  window.gtag("js", new Date()); window.gtag("config", "G-R8F1QX6HKC", { page_location: `${window.location.origin}${window.location.pathname}`, page_referrer: referrer });
  document.addEventListener("click", (event) => { const control = event.target.closest("[data-track]"); if (control?.dataset.track) window.gtag("event", "review_workspace_control", { control_id: control.dataset.track }); });
}
function track(name, details = {}) { window.gtag?.("event", name, details); }
function say(message) { liveStatus.textContent = message; }
function safeText(value, fallback = "Not available") { return String(value || fallback); }
function formatDate(value) { try { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)); } catch { return "Date unavailable"; } }
function accessHeaders() { return state.accessCode ? { "X-Review-Access": state.accessCode } : {}; }
function setBusy(button, busy, label) { button.disabled = busy; if (!button.dataset.label) button.dataset.label = button.textContent; button.textContent = busy ? label : button.dataset.label; }
function resetPendingAnalysis() { state.pendingAnalysis = null; }
function invalidateSample() { state.snapshot = null; resetPendingAnalysis(); samplePanel.hidden = true; updateRunState(); }
function analysisRequestId() { const signature = state.snapshot?.signature || ""; const key = `${signature}|${state.questionId}|${modelSelect.value}`; if (!state.pendingAnalysis || state.pendingAnalysis.key !== key) state.pendingAnalysis = { key, id: (crypto.randomUUID?.() || `${Date.now()}${Math.random()}`).replace(/[^A-Za-z0-9_-]/g, "") }; return state.pendingAnalysis.id; }
function showError(message) { $("#source-help").textContent = message; appUrl.setAttribute("aria-invalid", "true"); say(message); }
function clearError() { $("#source-help").textContent = "Paste a public store link, or type two or more letters to search App Store and Google Play."; appUrl.removeAttribute("aria-invalid"); }
function isStoreUrl(value) { try { const url = new URL(value); return url.protocol === "https:" && ["apps.apple.com", "play.google.com"].includes(url.hostname); } catch { return false; } }
function searchCountry() { return market.value.slice(-2).toLowerCase(); }
function cancelSearch() { if (state.searchTimer) window.clearTimeout(state.searchTimer); state.searchTimer = null; state.searchSequence += 1; state.searchController?.abort(); state.searchController = null; }
function closeSearchResults() { state.searchResults = []; state.activeSearchIndex = -1; appResults.replaceChildren(); appResults.hidden = true; appUrl.setAttribute("aria-expanded", "false"); appUrl.removeAttribute("aria-activedescendant"); }
function renderSearchResults() {
  appResults.replaceChildren(...state.searchResults.map((result, index) => {
    const item = document.createElement("li"); const button = document.createElement("button"); const copy = document.createElement("span"); const name = document.createElement("span"); const developer = document.createElement("span"); const source = document.createElement("span");
    button.type = "button"; button.className = "app-result"; button.id = `app-result-${index}`; button.dataset.resultIndex = String(index); button.dataset.track = "workspace_search_pick"; button.setAttribute("role", "option"); button.setAttribute("aria-selected", String(index === state.activeSearchIndex));
    name.className = "app-result__name"; name.textContent = result.name || "Unnamed app"; developer.className = "app-result__developer"; developer.textContent = result.developer || "Developer unavailable"; source.className = "app-result__source"; source.textContent = result.store === "app_store" ? "App Store" : "Google Play";
    copy.append(name, developer); button.append(copy, source); item.append(button); return item;
  }));
  const expanded = state.searchResults.length > 0; appResults.hidden = !expanded; appUrl.setAttribute("aria-expanded", String(expanded));
  if (state.activeSearchIndex >= 0) appUrl.setAttribute("aria-activedescendant", `app-result-${state.activeSearchIndex}`); else appUrl.removeAttribute("aria-activedescendant");
}
function chooseSearchResult(index) { const result = state.searchResults[index]; if (!result?.url) return; invalidateSample(); state.selectedUrl = result.url; appUrl.value = result.name || result.url; closeSearchResults(); clearError(); $("#source-help").textContent = `${result.store === "app_store" ? "App Store" : "Google Play"} result selected: ${result.name || "app"}.`; say("App selected."); }
async function searchApps(term, sequence) {
  state.searchController = new AbortController();
  try { const params = new URLSearchParams({ term, q: term, country: searchCountry() }); const response = await fetch(`/review-intel/api/search?${params}`, { headers: { Accept: "application/json" }, signal: state.searchController.signal }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "App search is unavailable."); if (sequence !== state.searchSequence || appUrl.value.trim() !== term) return; state.searchResults = Array.isArray(data.results) ? data.results.filter((result) => result && result.url) : []; state.activeSearchIndex = -1; renderSearchResults(); say(state.searchResults.length ? `${state.searchResults.length} app results available.` : "No matching apps found. Paste a store link instead."); } catch (error) { if (error?.name !== "AbortError" && sequence === state.searchSequence) { closeSearchResults(); say("App search is unavailable. You can still paste a store link."); } } finally { if (sequence === state.searchSequence) state.searchController = null; }
}
function handleAppInput() { clearError(); state.selectedUrl = ""; invalidateSample(); cancelSearch(); closeSearchResults(); const term = appUrl.value.trim(); if (isStoreUrl(term) || term.length < 2) return; const sequence = ++state.searchSequence; state.searchTimer = window.setTimeout(() => { state.searchTimer = null; void searchApps(term, sequence); }, 300); }
function handleAppKeydown(event) { if (!state.searchResults.length) return; if (event.key === "Escape") { event.preventDefault(); closeSearchResults(); return; } if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); const amount = event.key === "ArrowDown" ? 1 : -1; state.activeSearchIndex = (state.activeSearchIndex + amount + state.searchResults.length) % state.searchResults.length; renderSearchResults(); return; } if (event.key === "Enter" && state.activeSearchIndex >= 0) { event.preventDefault(); chooseSearchResult(state.activeSearchIndex); } }

function renderQuestions() {
  questionGroups.replaceChildren(...QUESTION_GROUPS.map((group) => {
    const button = document.createElement("button"); button.type = "button"; button.className = "group-button"; button.textContent = group.label; button.dataset.group = group.label; button.dataset.track = "workspace_question_group"; button.setAttribute("aria-pressed", String(group.label === state.activeGroup)); return button;
  }));
  const group = QUESTION_GROUPS.find((item) => item.label === state.activeGroup) || QUESTION_GROUPS[0];
  questions.replaceChildren(...group.questions.map((question) => {
    const button = document.createElement("button"); button.type = "button"; button.className = `question-option${question.id === state.questionId ? " is-selected" : ""}`; button.dataset.question = question.id; button.dataset.track = "workspace_question_select"; button.innerHTML = `<span><strong>${escapeHtml(question.label)}</strong><span>${escapeHtml(question.description)}</span></span>`; return button;
  }));
  $("#selected-question-copy").textContent = findQuestion(state.questionId).description;
}
function escapeHtml(value) { const node = document.createElement("div"); node.textContent = value ?? ""; return node.innerHTML; }
function renderConfig(config) {
  state.config = config || { configured: false, models: [], trialLimit: 3 };
  const ready = Boolean(state.config.configured); $("#connection-note").textContent = ready ? "Workspace ready" : "Setup in progress"; $(".mast-dot").className = `mast-dot ${ready ? "is-ready" : "is-error"}`;
  $("#setup-note").hidden = ready; modelSelect.replaceChildren();
  const models = Array.isArray(state.config.models) ? state.config.models : [];
  if (ready && models.length) models.forEach((model) => { const option = document.createElement("option"); option.value = model.id; option.textContent = model.label || model.id; modelSelect.append(option); });
  else { const option = document.createElement("option"); option.textContent = ready ? "No models are available" : "Live models appear after setup"; modelSelect.append(option); }
  modelSelect.disabled = !(ready && models.length); trialNote.textContent = ready ? `Up to ${state.config.trialLimit ?? 3} free analyses are planned. The service confirms your remaining allowance.` : "Live usage appears here when the workspace is connected.";
  updateRunState();
}
function exportedSnapshot(snapshot) { return snapshot?.export && typeof snapshot.export === "object" ? snapshot.export : snapshot || {}; }
function coverageText(coverage) { if (typeof coverage === "string") return coverage; if (!coverage || typeof coverage !== "object") return "Coverage details were not supplied."; const count = coverage.analyzed_ready ?? coverage.included ?? coverage.review_count ?? coverage.count; const start = coverage.date_from || coverage.oldest || coverage.startDate; const end = coverage.date_to || coverage.newest || coverage.endDate; return [count ? `${count} reviews` : null, start && end ? `${start} to ${end}` : null].filter(Boolean).join(" · ") || "Coverage details were not supplied."; }
function snapshotFacts(snapshot) {
  const exported = exportedSnapshot(snapshot); const reviews = Array.isArray(exported.reviews) ? exported.reviews : []; const app = exported.app || exported.product || {}; const count = exported.reviewCount || exported.coverage?.analyzed_ready || exported.coverage?.included || reviews.length; const dates = exported.dates || {};
  return [{ label: "App", value: app.name || exported.appName || "Selected app" }, { label: "Reviews", value: `${count} included` }, { label: "Market", value: exported.storefront?.label || exported.storefront?.name || exported.storefront?.country || market.options[market.selectedIndex]?.text || "Selected market" }, { label: "Date range", value: dates.oldest && dates.newest ? `${formatDate(dates.oldest)}–${formatDate(dates.newest)}` : exported.dateRange || coverageText(exported.coverage) }];
}
function renderSnapshot(snapshot) { state.snapshot = snapshot; resetPendingAnalysis(); sampleFacts.replaceChildren(...snapshotFacts(snapshot).map(({label,value}) => { const item = document.createElement("div"); item.innerHTML = `<dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd>`; return item; })); const exported = exportedSnapshot(snapshot); const citedCount = extractReviews(snapshot).length; const analyzedCount = exported?.coverage?.analyzed_ready || exported?.coverage?.included || exported?.reviewCount || citedCount; sampleCaption.textContent = snapshot?.demo?.evidenceSubset ? `${analyzedCount} reviews were analyzed for this saved example; ${citedCount} cited public reviews are included here for inspection.` : analyzedCount ? `This sample contains ${analyzedCount} public review${analyzedCount === 1 ? "" : "s"}. It is the evidence used for this report.` : "The returned sample did not include a review count."; samplePanel.hidden = false; updateRunState(); }
function updateRunState() { analyzeButton.disabled = !(state.config?.configured && state.snapshot?.signature && modelSelect.value); }
function extractReviews(snapshot) { const exported = exportedSnapshot(snapshot); return Array.isArray(exported.reviews) ? exported.reviews : Array.isArray(exported.items) ? exported.items : []; }
function reviewId(review, index) { return review?.review_id || review?.id || review?.reviewId || `Review ${index + 1}`; }
function findReviews(ids = [], snapshot = state.report?.sourceSnapshot || state.snapshot) { const wanted = new Set(ids.map(String)); return extractReviews(snapshot).filter((review, index) => wanted.has(String(reviewId(review,index)))); }
function reportMarkup(report) { const findings = Array.isArray(report?.findings) ? report.findings : []; const model = typeof report?.model === "object" ? report.model?.label || report.model?.id : report?.model; const questionTitle = report?.question?.id ? findQuestion(report.question.id).label : report?.id?.startsWith("saved-") ? "Saved example" : "Review analysis"; return `<header class="report-header"><p class="eyebrow">Analysis report</p><h2>${escapeHtml(questionTitle)}</h2><p class="report-answer">${escapeHtml(report?.answer || "No answer was returned.")}</p><p class="report-meta">${escapeHtml(model || "Model not identified")} · ${escapeHtml(formatDate(report?.createdAt))}</p></header><p class="coverage">${escapeHtml(coverageText(report?.coverage))}</p>${findings.map((finding, index) => { const count = finding?.evidence?.count; const denominator = finding?.evidence?.denominator; const percent = finding?.evidence?.percent; const evidenceLabel = count && denominator ? ` · Model tagged ${count} of ${denominator}${typeof percent === "number" ? ` (${percent}%)` : ""}` : Array.isArray(finding.reviewIds) ? ` · ${finding.reviewIds.length} cited review${finding.reviewIds.length === 1 ? "" : "s"}` : ""; const quotes = Array.isArray(finding.quotes) ? finding.quotes : []; return `<section class="finding"><div class="finding-tags"><span class="finding-status" data-status="${escapeHtml(finding.status || "")}">${escapeHtml(finding.status || "Finding")}</span><span class="finding-strength">${escapeHtml(finding.strength || "Strength unavailable")}</span></div><h3>${escapeHtml(finding.headline || `Finding ${index + 1}`)}</h3><p>${escapeHtml(finding.explanation || "Explanation unavailable.")}</p>${finding.implication ? `<p><strong>Why it matters:</strong> ${escapeHtml(finding.implication)}</p>` : ""}${finding.requirements ? `<p><strong>Check next:</strong> ${escapeHtml(finding.requirements)}</p>` : ""}${quotes.length ? `<blockquote class="finding-quote">“${escapeHtml(quotes[0].text)}”</blockquote>` : ""}<button type="button" class="evidence-button" data-evidence="${index}" data-track="workspace_open_evidence">Open source reviews${evidenceLabel}</button></section>`; }).join("")}<div class="report-actions"><button type="button" class="text-button" id="copy-report" data-track="workspace_copy_report" data-action="copy-report">Copy report</button><button type="button" class="text-button" id="export-report" data-track="workspace_export_report" data-action="export-report">Export .txt</button></div>`; }
function renderReport(report) { state.report = report; reportView.innerHTML = reportMarkup(report); reportView.hidden = false; reportEmpty.hidden = true; saveHistory(report); renderHistory(); }
function history() { try { return JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]"); } catch { return []; } }
function saveHistory(report) { const item = { id: report?.id || crypto.randomUUID?.() || String(Date.now()), answer: report?.answer || "Untitled report", createdAt: report?.createdAt || new Date().toISOString(), report, snapshot: report?.sourceSnapshot || state.snapshot }; const items = history().filter((entry) => entry.id !== item.id); items.unshift(item); try { localStorage.setItem(HISTORY_KEY, JSON.stringify(items.slice(0, 12))); } catch {} }
function renderHistory() { const items = history(); const root = $("#history-list"); root.replaceChildren(); if (!items.length) { root.textContent = "No reports have been saved in this browser yet."; return; } items.forEach((item) => { const row = document.createElement("div"); row.className = "history-row"; row.innerHTML = `<div><strong>${escapeHtml(item.answer)}</strong><span>${escapeHtml(formatDate(item.createdAt))}</span></div>`; const open = document.createElement("button"); open.type = "button"; open.className = "text-button"; open.textContent = "Open"; open.dataset.track = "workspace_open_history"; open.addEventListener("click", () => { state.snapshot = item.snapshot; renderSnapshot(item.snapshot); renderReport(item.report); showPanel("report"); }); row.append(open); root.append(row); }); }
function textExport() {
  const report = state.report || {}; const model = typeof report.model === "object" ? report.model?.label || report.model?.id : report.model; const source = exportedSnapshot(report.sourceSnapshot); const sourceName = source.app?.name || "Source app unavailable"; const sourceMarket = source.storefront?.label || source.storefront?.country_name || source.storefront?.country || "Source market unavailable";
  const lines = ["Review Intel report", "", `Created: ${formatDate(report.createdAt)}`, `Model: ${model || "Model not identified"}`, `Source: ${sourceName} · ${sourceMarket}`, `Coverage: ${coverageText(report.coverage)}`, "", "First useful read", report.answer || "No answer was returned."];
  (Array.isArray(report.findings) ? report.findings : []).forEach((finding, index) => { const evidence = finding?.evidence?.count && finding?.evidence?.denominator ? `${finding.evidence.count} of ${finding.evidence.denominator}${typeof finding.evidence.percent === "number" ? ` (${finding.evidence.percent}%)` : ""}` : `${Array.isArray(finding?.reviewIds) ? finding.reviewIds.length : 0} cited review(s)`; lines.push("", `Finding ${index + 1}: ${finding.headline || "Untitled finding"}`, `Status: ${finding.status || "Unavailable"}`, `Strength: ${finding.strength || "Unavailable"}`, `Validated evidence: ${evidence}`, `Explanation: ${finding.explanation || "Unavailable"}`); if (finding.implication) lines.push(`Why it matters: ${finding.implication}`); if (finding.requirements) lines.push(`Check next: ${finding.requirements}`); (Array.isArray(finding.quotes) ? finding.quotes : []).forEach((quote) => lines.push(`Evidence ${quote.reviewId || "ID unavailable"}: “${quote.text || "Quote unavailable"}”`)); });
  return lines.join("\n");
}
async function copyText(text, button) { try { await navigator.clipboard.writeText(text); const old = button.textContent; button.textContent = "Copied ✓"; setTimeout(() => { button.textContent = old; }, 2200); } catch { say("Copy failed. Select the text and copy it manually."); } }
function showPanel(name) { document.querySelectorAll(".tab").forEach((tab) => tab.classList.toggle("is-active", tab.dataset.panel === name)); document.querySelectorAll(".panel").forEach((panel) => { panel.hidden = panel.id !== `panel-${name}`; }); }
async function request(body) { const response = await fetch(API_URL, { method: body ? "POST" : "GET", headers: { Accept: "application/json", ...(body ? { "Content-Type": "application/json" } : {}), ...accessHeaders() }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({})); if (response.status === 401) { openAccess(); throw new Error("Access code required."); } if (!response.ok) throw new Error(data.error || "The workspace could not complete that request."); return data; }
async function loadDemo() { const response = await fetch(DEMO_URL, { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error("The saved demonstration is not available yet."); const demo = await response.json(); if (!demo.snapshot || !demo.report) throw new Error("The saved demonstration is incomplete."); renderSnapshot(demo.snapshot); renderReport(demo.report); showPanel("report"); say("Saved demonstration opened."); }
async function loadConfig() { try { renderConfig(await request()); } catch (error) { renderConfig({ configured: false, models: [], trialLimit: 3 }); $("#connection-note").textContent = "Setup unavailable"; } }
function openAccess() { if (!accessDialog.open) accessDialog.showModal(); }

questionGroups.addEventListener("click", (event) => { const button = event.target.closest("[data-group]"); if (!button) return; state.activeGroup = button.dataset.group; renderQuestions(); });
questions.addEventListener("click", (event) => { const button = event.target.closest("[data-question]"); if (!button) return; state.questionId = button.dataset.question; resetPendingAnalysis(); renderQuestions(); });
appUrl.addEventListener("input", handleAppInput); appUrl.addEventListener("keydown", handleAppKeydown); appResults.addEventListener("click", (event) => { const button = event.target.closest("[data-result-index]"); if (button) chooseSearchResult(Number(button.dataset.resultIndex)); }); market.addEventListener("change", () => { invalidateSample(); if (appUrl.value.trim().length >= 2 && !isStoreUrl(appUrl.value.trim())) handleAppInput(); }); limit.addEventListener("change", invalidateSample);
sourceForm.addEventListener("submit", async (event) => { event.preventDefault(); clearError(); const url = state.selectedUrl || (isStoreUrl(appUrl.value.trim()) ? appUrl.value.trim() : ""); if (!url) return showError("Choose an app from the results, or paste a public App Store or Google Play link."); if (!state.config?.configured) return showError("Live review retrieval is not connected yet. Open the saved demo to see the workspace with real saved data."); setBusy(sampleButton, true, "Getting sample…"); try { const data = await request({ action: "sample", url, market: market.value, questionId: state.questionId, limit: Number(limit.value) }); if (!data.snapshot) throw new Error("The service returned no review sample."); renderSnapshot(data.snapshot); say("Review sample ready."); } catch (error) { if (!/Access code required/.test(error.message)) showError(error.message); } finally { setBusy(sampleButton, false); } });
$("#open-demo").addEventListener("click", async () => { try { await loadDemo(); } catch (error) { showError(error.message); } });
$("#copy-sample").addEventListener("click", (event) => copyText(JSON.stringify(state.snapshot, null, 2), event.currentTarget));
modelSelect.addEventListener("change", resetPendingAnalysis);
analyzeButton.addEventListener("click", async () => { if (!state.warned) { warning.hidden = false; state.warned = true; analyzeButton.textContent = "Run analysis now"; say("Review the trial notice, then run the analysis again."); return; } setBusy(analyzeButton, true, "Reading reviews…"); try { const data = await request({ action: "analyze", snapshot: state.snapshot, questionId: state.questionId, modelId: modelSelect.value, requestId: analysisRequestId() }); if (!data.report) throw new Error("The service returned no report."); renderReport(data.report); if (typeof data.remaining !== "undefined") trialNote.textContent = `${data.remaining} trial report${data.remaining === 1 ? "" : "s"} remaining.`; showPanel("report"); say("Analysis report ready."); } catch (error) { if (!/Access code required/.test(error.message)) { warning.hidden = false; warning.textContent = error.message; } } finally { setBusy(analyzeButton, false); } });
document.querySelector(".tab-nav").addEventListener("click", (event) => { const tab = event.target.closest(".tab"); if (tab) showPanel(tab.dataset.panel); });
$("#clear-history").addEventListener("click", () => { try { localStorage.removeItem(HISTORY_KEY); } catch {} renderHistory(); });
reportView.addEventListener("click", (event) => { const evidence = event.target.closest("[data-evidence]"); if (evidence) { const finding = state.report?.findings?.[Number(evidence.dataset.evidence)] || {}; const reviews = findReviews(finding.reviewIds || []); const quotes = Array.isArray(finding.quotes) ? finding.quotes : []; $("#evidence-list").replaceChildren(...(reviews.length ? reviews : quotes).map((review, index) => { const item = document.createElement("article"); item.className = "evidence-review"; item.innerHTML = `<small>${escapeHtml(reviewId(review,index))}${review.rating ? ` · ${escapeHtml(review.rating)}★` : ""}</small><p>${escapeHtml(review.text || review.body || "Review text unavailable.")}</p>`; return item; })); $("#evidence-title").textContent = finding.headline || "Evidence"; state.evidenceTrigger = evidence; evidenceDialog.showModal(); } if (event.target.id === "copy-report") copyText(textExport(), event.target); if (event.target.id === "export-report") { const blob = new Blob([textExport()], { type: "text/plain" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "review-intel-report.txt"; link.click(); URL.revokeObjectURL(link.href); } });
$("#close-evidence").addEventListener("click", () => evidenceDialog.close()); evidenceDialog.addEventListener("close", () => { state.evidenceTrigger?.focus(); state.evidenceTrigger = null; }); $("#access-cancel").addEventListener("click", () => accessDialog.close()); $("#access-form").addEventListener("submit", async (event) => { event.preventDefault(); const code = $("#access-code").value.trim(); if (!code) { $("#access-error").textContent = "Enter the access code to continue."; return; } state.accessCode = code; $("#access-error").textContent = ""; accessDialog.close(); await loadConfig(); });
initializeAnalytics(); renderQuestions(); renderHistory(); $("#enter-access").addEventListener("click", openAccess); loadConfig();
